### PR TITLE
Add lifetime parameters

### PR DESCRIPTION
**Pull request by oakes**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Then I wait @gkoz PR.

**Comment by gkoz** [comment]
@GuillaumeGomez I was mistaken, my suggestion didn't work as is. It would require that you also bind `F` by `'static`, and I can't say whichever way is more correct. Static would be more conservative for sure (`Send` required `'static` until now). But I don't understand `c_vec` enough yet to make a judgment call. What's you opinion?

```
--- a/src/c_vec.rs
+++ b/src/c_vec.rs
@@ -48,7 +48,7 @@ use std::thunk::{Thunk};
 pub struct CVec<T> {
     base: *mut T,
     len: usize,
-    dtor: Option<Thunk>,
+    dtor: Option<Thunk<'static>>,
 }

 #[unsafe_destructor]
@@ -95,7 +95,7 @@ impl<T> CVec<T> {
                                    len: usize,
                                    dtor: F)
                                    -> CVec<T>
-        where F : FnOnce(), F : Send
+        where F : FnOnce() + Send + 'static
     {
         assert!(base != ptr::null_mut());
         let dtor: Thunk = Thunk::new(dtor);
```

**Comment by GuillaumeGomez** [comment]
I'd prefer avoid static lifetime on a raw pointer actually. For the moment I'll just merge like that, I'll come back to it later. Thanks to both of you !

**Comment by kornelski** [comment]
Is there a documentation for this? I don't understand what happened here.

It broke my code, but I don't know what lifetime I need to add.

**Comment by gkoz** [comment]
@pornel can you explain how exactly it broke your code or why `'static` didn't work for you?

**Comment by gkoz** [comment]
@GuillaumeGomez FWIW semver conventions would require bumping the version to `2.0` when breaking the API. I guess that's why they recommend against releasing `1.0` versions before Rust itself reaches `1.0` ;)

**Comment by kornelski** [comment]
The type signature started requiring a lifetime. I've been using v1.0.1 before that didn't have lifetime exposed. 

`'static` made it compile, but since I don't know what it's for I wasn't sure whether that's correct. I was wondering whether that needed to be a lifetime of data pointed to, lifetime of dtor closure or it's something magic like PhantomData type.

**Comment by gkoz** [comment]
As far as I understand it, it is the lifetime of any references the destructor closure might have borrowed, which was `'static` before this change because `Send` required `'static` until then. Therefore any code predating this change can just use `'static` because that has been the requirement all along. New code could theoretically use other lifetimes but I doubt it would make much sense for destructors. So maybe the lifetime parameter shouldn't have been added until someone asked for it.

**Comment by gkoz** [comment]
Another idea I've just had: isn't it weird that `drop` doesn't pass `self.base` to the destructor? Wouldn't that make everyones' life easier?

**Comment by GuillaumeGomez** [comment]
Apparently it's broken once again. I'll take a look tonight.

**Comment by GuillaumeGomez** [comment]
@gkoz: I only update when there is breaking change (or almost), so it would be annoying to update to the next major version each time.

@pornel: can you open an issue where you give a full description of your problem or even a link to your repo please ?

**Comment by kornelski** [comment]
@GuillaumeGomez #3

**Pull request merged**
