### PR TITLE
Update libc dependency from 0.1 to 0.2

### PR DESCRIPTION
**Pull request by felixc**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
0.1.1 would be better. :)

**Comment by felixc** [comment]
Sorry, I don't understand… libc 0.1.1 is also outdated, isn't it?

**Comment by GuillaumeGomez** [comment]
Oh sorry. Thought it was for c_vec version, I read it too quickly... Then it's all good. Thanks!

**Comment by felixc** [comment]
Oh, I see, yeah, I guess maybe there should be a point release for these two fixes too?

I also only just realized you have two branches, the 1.0.12 (master) and the 1.1.0 one, and I'm not sure if both should get the patches? Anything I can do to help?

**Comment by GuillaumeGomez** [comment]
A branch was for rustc release version compatibility. So no, you did good.

**Pull request merged**
